### ISSUE TITLE
不用混淆吗？开启混淆就不能写日志了

### ISSUE THREAD

**Issue by xhh1993** [TencentCloud/tencentcloud-cls-sdk-android#3]
不用混淆吗？开启混淆就不能写日志了

**Comment by skypan-yes** [comment]
同样的问题。在官方群里问，也没人回答。

**Comment by xhh1993** [comment]
根据报错信息自己添加混淆吧，我们这是加了 -keep class net.jpountz.lz4.** { *; } 就OK了

**Comment by wgliang** [comment]
可以查看
https://github.com/TencentCloud/tencentcloud-cls-sdk-android#%E6%B7%B7%E6%B7%86%E5%BC%82%E5%B8%B8
