### ISSUE TITLE
是否支持获取客户端公网出口IP地址？

### ISSUE THREAD

**Issue by crzqj** [TencentCloud/tencentcloud-cls-sdk-android#4]
I have a few data reported to the CLS via the SDK. Currently the __source__ field defaults to my local network address. Can I get a public IP address?

**Comment by wgliang** [comment]
在CLS控制台查看日志的时候有一个Source字段，这个字段就是公网的出口IP

**Comment by crzqj** [comment]
Source字段好像是本地IP（内网地址），并不是公网出口IP

**Comment by wgliang** [comment]
> 

走内网的话不会走公网出口的，只有在外网情况下才会有

**Comment by farmerx** [comment]
@crzqj  4月中旬 andriod sdk source 会从服务端获取，变成公网出口ip
